name: deploy website
on: pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: lint
        run: npm run lint
      - name: unit test
        run: npm run test
      - name: build styleguide
        run: npm run document:build
      - name: create docs path
        run: npm run createDocs
      - name: build
        run: npm run build
        env:
          STORYBLOK_API_KEY: ${{ secrets.STORYBLOK_API_KEY }}
      - uses: amondnet/vercel-action@v19.0.1+4
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_TEAM_ID }}
